CREATE TABLE Endereco (
    ID_ENDERECO INT AUTO_INCREMENT PRIMARY KEY,
    CEP VARCHAR(10),
    Rua VARCHAR(100),
    Bairro VARCHAR(50),
    Cidade VARCHAR(50)
);

CREATE TABLE Administrador (
    ID_ADMIN INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100),
    CPF_CNPJ VARCHAR(14),
    Data_Nascimento DATE,
    Email VARCHAR(100),
    ID_ENDERECO INT,
    FOREIGN KEY (ID_ENDERECO) REFERENCES Endereco(ID_ENDERECO)
);

CREATE TABLE Saloes (
    ID_SALAO INT AUTO_INCREMENT PRIMARY KEY,
    Servicos_Desejados VARCHAR(255),
    ID_ADMIN INT,
    FOREIGN KEY (ID_ADMIN) REFERENCES Administrador(ID_ADMIN),
    FOREIGN KEY (ID_ADMIN) REFERENCES Administrador(ID_ADMIN)
);

CREATE TABLE Clientes (
    ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
    Servicos_Desejados VARCHAR(255),
    ID_ADMIN INT,
    FOREIGN KEY (ID_ADMIN) REFERENCES Administrador(ID_ADMIN)
);